name: Release

on:
  push:
    tags:
      - 'v*'   # Déclenchement quand un tag vX est poussé

permissions:
  contents: write

jobs:
  release:
    if: startsWith(github.ref_name, 'v')   # Condition basée sur le tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install php composer -y

      - name: Build release
        run: make all appstore

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create latest ./build/artifacts/spreed.tar.gz
